
#工作名字
name: Library-reservation-of-gzhu

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  31 22 * * *  

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pycryptodome
        mv /opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/crypto /opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/Crypto
    - name: Checkin
      run: |
        python3 ./main.py 
